### ISSUE TITLE
Magento 2 support?

### ISSUE THREAD

**Issue by mixmastermike** [TriggeredMessaging/digitalDataMagentoExtension#18]
Do you plan on supporting Magento 2?
Thanks!

**Comment by mixmastermike** [comment]
bump

**Comment by MikeTheTechie** [comment]
Yes, it's on the plan but won't be quick as extensions for Magento 2 require a complete re-write from Magento 1.x

**Comment by mixmastermike** [comment]
Ok, thank you

**Comment by dhendo** [comment]
@mixmastermike a new version for M2 is on the Marketplace: https://marketplace.magento.com/freshrelevance-digitaldatalayer.html
