### ISSUE TITLE
Undefined offset: 0  inapp/code/community/TriggeredMessaging/DigitalDataLayer/Model/Page/Observer.php

### ISSUE THREAD

**Issue by joolswills** [TriggeredMessaging/digitalDataMagentoExtension#7]
https://github.com/TriggeredMessaging/digitalDataMagentoExtension/blob/master/app/code/community/TriggeredMessaging/DigitalDataLayer/Model/Page/Observer.php#L756

It would be better to use is_array

**Comment by dhendo** [comment]
Thanks for the prod @joolswills - will get on it.
